namespace IndTrace.Application.Products.Services;

/// <summary>
/// Orchestrates sophisticated product persistence with intelligent ID assignment.
/// Handles complex persistence strategy from original handler including dual AddAsync patterns.
/// Preserves EXACT persistence logic and ID assignment algorithms.
/// </summary>
public class ProductPersistenceOrchestrator : IProductPersistenceOrchestrator
{
    private readonly IRepository<Product> _productRepository;
    private readonly IProductFactory _productFactory;
    private readonly IProductUniquenessValidator _productUniquenessValidator;
    private readonly ILogger<ProductPersistenceOrchestrator> _logger;

    public ProductPersistenceOrchestrator(
        IRepository<Product> productRepository,
        IProductFactory productFactory,
        IProductUniquenessValidator productUniquenessValidator,
        ILogger<ProductPersistenceOrchestrator> logger)
    {
        _productRepository = productRepository ?? throw new ArgumentNullException(nameof(productRepository));
        _productFactory = productFactory ?? throw new ArgumentNullException(nameof(productFactory));
        _productUniquenessValidator = productUniquenessValidator ?? throw new ArgumentNullException(nameof(productUniquenessValidator));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Creates and persists a product using provided parsed id and dynamic offset when available.
    /// Falls back to auto id when the calculated id is not available.
    /// </summary>
    public async Task<Result<Product>> CreateProductWithIntelligentIdAsync(
        Product product,
        int parsedId,
        int dynamicOffset,
        CancellationToken cancellationToken)
    {
        if (product is null)
        {
            return Result<Product>.WithFailure("Product cannot be null.");
        }

        var proposedId = CalculateAdjustedProductId(parsedId, dynamicOffset);
        var isAvailable = await _productUniquenessValidator
            .IsProductIdAvailableAsync(proposedId, cancellationToken)
            .ConfigureAwait(false);

        if (isAvailable)
        {
            return await CreateProductWithSpecificIdAsync(product, proposedId, "Products", cancellationToken)
                .ConfigureAwait(false);
        }

        return await CreateProductWithAutoIdAsync(product, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Persists a product with database-assigned id.
    /// </summary>
    public async Task<Result<Product>> CreateProductWithAutoIdAsync(
        Product product,
        CancellationToken cancellationToken)
    {
        if (product is null)
        {
            return Result<Product>.WithFailure("Product cannot be null.");
        }

        product.ProductId = 0;
        var result = await _productRepository.AddAsync(product, cancellationToken).ConfigureAwait(false);
        return result.IsFailure ? Result<Product>.WithFailure(result.Errors) : Result<Product>.Success(product);
    }

    /// <summary>
    /// Persists a product with a specific id into a specific table.
    /// </summary>
    public async Task<Result<Product>> CreateProductWithSpecificIdAsync(
        Product product,
        int productId,
        string tableName,
        CancellationToken cancellationToken)
    {
        if (product is null)
        {
            return Result<Product>.WithFailure("Product cannot be null.");
        }

        product.ProductId = productId;
        var result = await _productRepository
            .AddAsync(product, productId, tableName, cancellationToken)
            .ConfigureAwait(false);

        return result.IsFailure ? Result<Product>.WithFailure(result.Errors) : Result<Product>.Success(product);
    }

    /// <summary>
    /// Decides the best persistence method based on availability of the calculated id.
    /// </summary>
    public async Task<Result<ProductPersistenceStrategy>> DeterminePersistenceStrategyAsync(
        Product product,
        int parsedId,
        int dynamicOffset,
        CancellationToken cancellationToken)
    {
        if (product is null)
        {
            return Result<ProductPersistenceStrategy>.WithFailure("Product cannot be null.");
        }

        var proposedId = CalculateAdjustedProductId(parsedId, dynamicOffset);
        var isAvailable = await _productUniquenessValidator
            .IsProductIdAvailableAsync(proposedId, cancellationToken)
            .ConfigureAwait(false);

        var method = isAvailable ? PersistenceMethod.IntelligentIdAssignment : PersistenceMethod.AutoGeneratedId;
        var rationale = isAvailable ? "Calculated ProductId available" : "Calculated ProductId unavailable";

        return Result<ProductPersistenceStrategy>.Success(new ProductPersistenceStrategy
        {
            Method = method,
            ProposedProductId = isAvailable ? proposedId : 0,
            Rationale = rationale,
            IsIntelligentAssignment = isAvailable
        });
    }

    /// <summary>
    /// Calculates adjusted product id from parsed suffix and dynamic offset.
    /// </summary>
    public int CalculateAdjustedProductId(int parsedId, int dynamicOffset)
    {
        if (parsedId <= 0)
        {
            return 0;
        }

        return parsedId + dynamicOffset;
    }

    /// <summary>
    /// Persists product using sophisticated ID assignment strategy.
    /// Implements EXACT persistence logic from original handler with intelligent ID parsing.
    /// </summary>
    public async Task<Result<Product>> PersistProductWithIntelligentIdAsync(
        Product product,
        ProductInput productInput,
        CancellationToken cancellationToken)
    {
        // Early cancellation check
        if (cancellationToken.IsCancellationRequested)
        {
            return Result<Product>.WithFailure("Operation was canceled.");
        }

        // Null guards for dependencies and parameters
        if (_productRepository is null)
        {
            return Result<Product>.WithFailure("Product repository cannot be null.");
        }

        if (_productFactory is null)
        {
            return Result<Product>.WithFailure("Product factory cannot be null.");
        }

        if (_productUniquenessValidator is null)
        {
            return Result<Product>.WithFailure("Product uniqueness validator cannot be null.");
        }

        if (product is null)
        {
            return Result<Product>.WithFailure("Product cannot be null for persistence.");
        }

        if (productInput is null)
        {
            return Result<Product>.WithFailure("ProductInput cannot be null for persistence.");
        }

        try
        {
            _logger.LogDebug("Starting sophisticated product persistence for PartNumber: {PartNumber}",
                product.PartNumber);

            // SOPHISTICATED ID ASSIGNMENT STRATEGY - Critical business logic from original handler
            var idAssignmentResult = await AssignIntelligentProductIdAsync(product, productInput, cancellationToken)
                .ConfigureAwait(false);

            if (idAssignmentResult.IsFailure || idAssignmentResult.Value is null)
            {
                _logger.LogError("Product ID assignment failed for PartNumber: {PartNumber}", product.PartNumber);
                return Result<Product>.WithFailure(idAssignmentResult.Errors);
            }

            // Determine persistence strategy based on ID assignment results
            var persistenceResult = await ExecutePersistenceStrategyAsync(product, idAssignmentResult.Value, cancellationToken)
                .ConfigureAwait(false);

            if (persistenceResult.IsFailure)
            {
                _logger.LogError("Product persistence failed for PartNumber: {PartNumber}", product.PartNumber);
                return Result<Product>.WithFailure(persistenceResult.Errors);
            }

            _logger.LogDebug("Product persistence successful. ProductId: {ProductId}, PartNumber: {PartNumber}",
                product.ProductId, product.PartNumber);

            return Result<Product>.Success(product);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred while persisting product for PartNumber: {PartNumber}",
                product.PartNumber);
            return Result<Product>.WithFailure($"Exception occurred while persisting product: {ex.Message}");
        }
    }

    /// <summary>
    /// Assigns intelligent ProductId using sophisticated parsing and availability logic.
    /// Preserves EXACT ID assignment algorithm from original handler.
    /// </summary>
    private async Task<Result<ProductIdAssignmentStrategy>> AssignIntelligentProductIdAsync(
        Product product,
        ProductInput productInput,
        CancellationToken cancellationToken)
    {
        try
        {
            _logger.LogDebug("Analyzing PartNumber for intelligent ID assignment: {PartNumber}", product.PartNumber);

            // STEP 1: Attempt to parse integer from PartNumber using exact algorithm
            var parseResult = _productFactory.TryParseLastInteger(product.PartNumber);

            if (!parseResult.Success)
            {
                _logger.LogDebug("No integer found in PartNumber, using random ID generation strategy");

                // Generate a random unused ProductId since Products table doesn't have auto-increment
                var randomProductId = await FindAvailableProductIdAsync(IdGenerationStrategy.Random, 0, cancellationToken).ConfigureAwait(false);

                return Result<ProductIdAssignmentStrategy>.Success(new ProductIdAssignmentStrategy
                {
                    Strategy = PersistenceStrategy.IntelligentAssign, // Use IntelligentAssign with generated ID
                    TargetProductId = randomProductId,
                    ParsedNumber = null,
                    DynamicOffset = 0
                });
            }

            var parsedNumber = parseResult.ParsedId;
            _logger.LogDebug("Parsed number from PartNumber: {ParsedNumber}", parsedNumber);

            // STEP 2: Calculate dynamic offset using exact algorithm from original handler
            var dynamicOffset = _productFactory.GetDynamicOffset(parsedNumber);
            var targetProductId = parsedNumber + dynamicOffset;

            _logger.LogDebug("Calculated dynamic offset: {DynamicOffset}, Target ProductId: {TargetProductId}",
                dynamicOffset, targetProductId);

            // STEP 3: Check if calculated ProductId is available
            var isAvailable = await _productUniquenessValidator.IsProductIdAvailableAsync(targetProductId, cancellationToken)
                .ConfigureAwait(false);

            if (isAvailable)
            {
                _logger.LogDebug("Target ProductId {TargetProductId} is available, using intelligent assignment", targetProductId);
                return Result<ProductIdAssignmentStrategy>.Success(new ProductIdAssignmentStrategy
                {
                    Strategy = PersistenceStrategy.IntelligentAssign,
                    TargetProductId = targetProductId,
                    ParsedNumber = parsedNumber,
                    DynamicOffset = dynamicOffset
                });
            }
            else
            {
                _logger.LogDebug("Target ProductId {TargetProductId} is not available, starting resilient aligned ID search", targetProductId);

                // STEP 4: RESILIENT ALIGNED ID SEARCH - Business Logic from User
                // If L67897 (ID 67897) is not available, search 167897, 267897, 367897, etc.
                var alignedId = await FindAvailableProductIdAsync(IdGenerationStrategy.AlignedSearch, parsedNumber, cancellationToken)
                    .ConfigureAwait(false);

                if (alignedId > 0)
                {
                    _logger.LogDebug("Found available aligned ProductId {AlignedId} for parsed number {ParsedNumber}", alignedId, parsedNumber);
                    return Result<ProductIdAssignmentStrategy>.Success(new ProductIdAssignmentStrategy
                    {
                        Strategy = PersistenceStrategy.IntelligentAssign,
                        TargetProductId = alignedId,
                        ParsedNumber = parsedNumber,
                        DynamicOffset = alignedId - parsedNumber // Calculate actual offset used
                    });
                }
                else
                {
                    _logger.LogDebug("No available aligned ProductId found for parsed number {ParsedNumber}, falling back to auto-assignment", parsedNumber);
                    return Result<ProductIdAssignmentStrategy>.Success(new ProductIdAssignmentStrategy
                    {
                        Strategy = PersistenceStrategy.AutoAssign,
                        TargetProductId = 0,
                        ParsedNumber = parsedNumber,
                        DynamicOffset = dynamicOffset
                    });
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred during intelligent ID assignment for PartNumber: {PartNumber}",
                product.PartNumber);
            return Result<ProductIdAssignmentStrategy>.WithFailure($"Exception during ID assignment: {ex.Message}");
        }
    }

    /// <summary>
    /// Executes persistence strategy based on ID assignment results.
    /// Implements EXACT dual AddAsync strategy from original handler.
    /// </summary>
    private async Task<Result> ExecutePersistenceStrategyAsync(
        Product product,
        ProductIdAssignmentStrategy strategy,
        CancellationToken cancellationToken)
    {
        try
        {
            _logger.LogDebug("Executing persistence strategy: {Strategy} for Product: {PartNumber}",
                strategy.Strategy, product.PartNumber);

            Result persistenceResult;

            if (strategy.Strategy == PersistenceStrategy.IntelligentAssign)
            {
                // INTELLIGENT ASSIGNMENT: Use 4-parameter AddAsync with specific ProductId
                _logger.LogDebug("Using 4-parameter AddAsync with ProductId: {ProductId}", strategy.TargetProductId);

                // Set the calculated ProductId before persistence
                product.ProductId = strategy.TargetProductId;

                // Use 4-parameter AddAsync: (entity, id, tableName, cancellationToken)
                persistenceResult = await _productRepository.AddAsync(
                    product,
                    strategy.TargetProductId,
                    "Products",
                    cancellationToken)
                    .ConfigureAwait(false);
            }
            else
            {
                // AUTO ASSIGNMENT: Use 2-parameter AddAsync for automatic ID assignment
                _logger.LogDebug("Using 2-parameter AddAsync for automatic ID assignment");

                // Ensure ProductId is 0 for auto-assignment
                product.ProductId = 0;

                // Use 2-parameter AddAsync: (entity, cancellationToken)
                persistenceResult = await _productRepository.AddAsync(product, cancellationToken)
                    .ConfigureAwait(false);
            }

            if (persistenceResult.IsFailure)
            {
                _logger.LogError("Persistence failed for strategy: {Strategy}, Product: {PartNumber}",
                    strategy.Strategy, product.PartNumber);
                return persistenceResult;
            }

            _logger.LogDebug("Persistence successful using strategy: {Strategy}, Final ProductId: {ProductId}",
                strategy.Strategy, product.ProductId);

            return Result.Success();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred during persistence execution for Product: {PartNumber}",
                product.PartNumber);
            return Result.WithFailure($"Exception during persistence execution: {ex.Message}");
        }
    }

    /// <summary>
    /// Validates product readiness for persistence.
    /// Ensures all required data is present before attempting persistence.
    /// </summary>
    public Result ValidateProductForPersistence(Product product)
    {
        if (product is null)
        {
            return Result.WithFailure("Product cannot be null for persistence validation.");
        }

        var errors = new List<string>();

        // Core product validation
        if (string.IsNullOrWhiteSpace(product.PartNumber))
        {
            errors.Add("Product PartNumber is required for persistence.");
        }

        if (string.IsNullOrWhiteSpace(product.ProductName))
        {
            errors.Add("Product ProductName is required for persistence.");
        }

        // Customer relationship validation
        if (product.CustomerId <= 0)
        {
            errors.Add("Product must have a valid CustomerId for persistence.");
        }

        if (product.Customer is null)
        {
            errors.Add("Product must have a Customer entity for persistence.");
        }

        // Line relationship validation
        if (product.LineId <= 0)
        {
            errors.Add("Product must have a valid LineId for persistence.");
        }

        if (product.Line is null)
        {
            errors.Add("Product must have a Line entity for persistence.");
        }

        // Audit field validation
        if (string.IsNullOrWhiteSpace(product.CreatedBy))
        {
            errors.Add("Product CreatedBy is required for persistence.");
        }

        return errors.Count > 0
            ? Result.WithFailure(errors)
            : Result.Success();
    }

    /// <summary>
    /// Updates an existing product using intelligent persistence strategy.
    /// Handles product updates while preserving ID assignment logic.
    /// </summary>
    public async Task<Result<Product>> UpdateProductWithIntelligentStrategyAsync(
        Product product,
        ProductInput productInput,
        CancellationToken cancellationToken)
    {
        // Early cancellation check
        if (cancellationToken.IsCancellationRequested)
        {
            return Result<Product>.WithFailure("Operation was canceled.");
        }

        // Null guards for dependencies and parameters
        if (_productRepository is null)
        {
            return Result<Product>.WithFailure("Product repository cannot be null.");
        }

        if (product is null)
        {
            return Result<Product>.WithFailure("Product cannot be null for update.");
        }

        if (productInput is null)
        {
            return Result<Product>.WithFailure("ProductInput cannot be null for update.");
        }

        try
        {
            _logger.LogDebug("Updating product with intelligent strategy. ProductId: {ProductId}", product.ProductId);

            // Update audit fields
            product.ModifiedBy = productInput.CreatedBy ?? product.ModifiedBy;
            product.ModifiedOn = DateTime.Now;

            // Execute update
            var updateResult = await _productRepository.UpdateAsync(product, cancellationToken)
                .ConfigureAwait(false);

            if (updateResult.IsFailure)
            {
                _logger.LogError("Product update failed for ProductId: {ProductId}", product.ProductId);
                return Result<Product>.WithFailure(updateResult.Errors);
            }

            _logger.LogDebug("Product update successful. ProductId: {ProductId}", product.ProductId);
            return Result<Product>.Success(product);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred while updating product ProductId: {ProductId}", product.ProductId);
            return Result<Product>.WithFailure($"Exception occurred while updating product: {ex.Message}");
        }
    }

    /// <summary>
    /// Represents the ID assignment strategy for product persistence.
    /// Encapsulates the persistence strategy and calculated values.
    /// </summary>
    private class ProductIdAssignmentStrategy
    {
        public PersistenceStrategy Strategy { get; set; }
        public int TargetProductId { get; set; }
        public int? ParsedNumber { get; set; }
        public int DynamicOffset { get; set; }
    }

    /// <summary>
    /// Unified ProductId generation strategy that handles both random and aligned search patterns.
    /// Applies DRY principle by consolidating ID availability checking logic.
    /// </summary>
    /// <param name="strategy">The ID generation strategy to use</param>
    /// <param name="baseId">Base ID for aligned search, or 0 for random generation</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Available ProductId, or 0 if no ID found within limits</returns>
    private async Task<int> FindAvailableProductIdAsync(IdGenerationStrategy strategy, int baseId, CancellationToken cancellationToken)
    {
        switch (strategy)
        {
            case IdGenerationStrategy.Random:
                return await GenerateRandomProductIdAsync(cancellationToken).ConfigureAwait(false);

            case IdGenerationStrategy.AlignedSearch:
                return await SearchAlignedProductIdAsync(baseId, cancellationToken).ConfigureAwait(false);

            default:
                _logger.LogWarning("Unknown ID generation strategy: {Strategy}, falling back to random", strategy);
                return await GenerateRandomProductIdAsync(cancellationToken).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Generates a random unused ProductId with collision detection.
    /// Uses range 1000-99999 to avoid conflicts with parsed IDs from part numbers.
    /// </summary>
    private async Task<int> GenerateRandomProductIdAsync(CancellationToken cancellationToken)
    {
        const int maxAttempts = 10;
        const int minRange = 1000;
        const int maxRange = 100000;
        var random = new Random();

        _logger.LogDebug("Starting random ProductId generation (range: {MinRange}-{MaxRange})", minRange, maxRange - 1);

        for (int attempt = 0; attempt < maxAttempts; attempt++)
        {
            var candidateId = random.Next(minRange, maxRange);

            _logger.LogDebug("Checking random candidate ProductId: {CandidateId} (attempt {Attempt}/{MaxAttempts})",
                candidateId, attempt + 1, maxAttempts);

            if (await IsProductIdAvailableInternalAsync(candidateId, cancellationToken).ConfigureAwait(false))
            {
                _logger.LogDebug("Found available random ProductId: {ProductId} after {Attempts} attempts", candidateId, attempt + 1);
                return candidateId;
            }
        }

        // Fallback: Use timestamp-based ID if random generation fails
        var timestampId = (int)(DateTimeOffset.UtcNow.ToUnixTimeSeconds() % 1000000);
        _logger.LogWarning("Random ID generation failed after {MaxAttempts} attempts, using timestamp fallback: {ProductId}",
            maxAttempts, timestampId);

        return timestampId;
    }

    /// <summary>
    /// Searches for available aligned ProductId using resilient pattern.
    /// L67897 → 67897 → 167897 → 267897 → 367897, etc.
    /// Maintains visual alignment between part numbers and ProductIds.
    /// </summary>
    private async Task<int> SearchAlignedProductIdAsync(int baseId, CancellationToken cancellationToken)
    {
        const int maxSearchMultiplier = 9; // Search up to 967897 for baseId 67897

        _logger.LogDebug("Starting aligned ProductId search for base ID: {BaseId}", baseId);

        // Calculate increment based on base ID length
        var baseIdLength = baseId.ToString().Length;
        var incrementValue = (int)Math.Pow(10, baseIdLength);

        _logger.LogDebug("Base ID: {BaseId} ({Length} digits), increment: {IncrementValue}",
            baseId, baseIdLength, incrementValue);

        for (int multiplier = 1; multiplier <= maxSearchMultiplier; multiplier++)
        {
            var candidateId = (multiplier * incrementValue) + baseId;

            _logger.LogDebug("Checking aligned candidate ProductId: {CandidateId} (base: {BaseId}, multiplier: {Multiplier})",
                candidateId, baseId, multiplier);

            if (await IsProductIdAvailableInternalAsync(candidateId, cancellationToken).ConfigureAwait(false))
            {
                _logger.LogDebug("Found available aligned ProductId: {CandidateId} for base: {BaseId}", candidateId, baseId);
                return candidateId;
            }
        }

        _logger.LogWarning("Aligned ID search exhausted for base: {BaseId} (searched {MaxMultiplier} variations)",
            baseId, maxSearchMultiplier);

        return 0; // No aligned ID found
    }

    /// <summary>
    /// Internal helper to check ProductId availability with consistent error handling.
    /// Centralizes availability checking logic to ensure consistency.
    /// </summary>
    private async Task<bool> IsProductIdAvailableInternalAsync(int productId, CancellationToken cancellationToken)
    {
        try
        {
            return await _productUniquenessValidator
                .IsProductIdAvailableAsync(productId, cancellationToken)
                .ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error checking availability for ProductId: {ProductId}", productId);
            return false; // Assume unavailable on error for safety
        }
    }

    /// <summary>
    /// Enumeration of ID generation strategies.
    /// Defines the different approaches for finding available ProductIds.
    /// </summary>
    private enum IdGenerationStrategy
    {
        Random,         // Generate random IDs with collision detection
        AlignedSearch   // Search for aligned IDs (67897 → 167897 → 267897, etc.)
    }

    /// <summary>
    /// Enumeration of persistence strategies.
    /// Defines the different approaches for product ID assignment.
    /// </summary>
    private enum PersistenceStrategy
    {
        AutoAssign,        // Use 2-parameter AddAsync for automatic ID assignment
        IntelligentAssign  // Use 4-parameter AddAsync with calculated ProductId
    }
}
