namespace IndFusion.Mcp.Core.Abstractions;

/// <summary>
/// Request for semantic code search operations.
/// </summary>
/// <param name="Query">Semantic search query.</param>
/// <param name="RepositoryScope">Scope of the repository to search.</param>
/// <param name="MaxResults">Maximum number of results to return.</param>
/// <param name="SimilarityThreshold">Minimum similarity threshold for results.</param>
/// <param name="IncludeMetadata">Whether to include metadata in results.</param>
/// <param name="SearchOptions">Additional search options.</param>
public record SemanticSearchRequest(
    string Query,
    string RepositoryScope,
    int MaxResults = 10,
    double SimilarityThreshold = 0.7,
    bool IncludeMetadata = true,
    Dictionary<string, object>? SearchOptions = null
);

/// <summary>
/// Request for code pattern analysis operations.
/// </summary>
/// <param name="CodeSnippet">Code snippet to analyze.</param>
/// <param name="AnalysisType">Type of analysis to perform.</param>
/// <param name="Context">Additional context for analysis.</param>
/// <param name="IncludeSuggestions">Whether to include improvement suggestions.</param>
/// <param name="ConfidenceThreshold">Minimum confidence threshold for results.</param>
public record CodePatternAnalysisRequest(
    string CodeSnippet,
    string AnalysisType,
    Dictionary<string, object>? Context = null,
    bool IncludeSuggestions = true,
    double ConfidenceThreshold = 0.8
);

/// <summary>
/// Request for knowledge base operations.
/// </summary>
/// <param name="Operation">Type of knowledge base operation.</param>
/// <param name="EntityId">ID of the entity to operate on.</param>
/// <param name="EntityType">Type of the entity.</param>
/// <param name="Data">Data for the operation.</param>
/// <param name="Metadata">Additional metadata.</param>
public record KnowledgeBaseRequest(
    string Operation,
    string EntityId,
    string EntityType,
    Dictionary<string, object> Data,
    Dictionary<string, object>? Metadata = null
);

/// <summary>
/// Request for RAG query operations.
/// </summary>
/// <param name="Question">Question to ask the RAG system.</param>
/// <param name="Context">Additional context for the question.</param>
/// <param name="MaxTokens">Maximum number of tokens in response.</param>
/// <param name="Temperature">Temperature for response generation.</param>
/// <param name="IncludeSources">Whether to include source citations.</param>
public record RagQueryRequest(
    string Question,
    Dictionary<string, object>? Context = null,
    int MaxTokens = 1000,
    double Temperature = 0.7,
    bool IncludeSources = true
);

/// <summary>
/// Result of semantic search operations.
/// </summary>
/// <param name="Success">Whether the search succeeded.</param>
/// <param name="Results">Search results.</param>
/// <param name="TotalMatches">Total number of matches found.</param>
/// <param name="SearchTimeMs">Time taken for the search.</param>
/// <param name="QueryProcessed">The processed query used for search.</param>
/// <param name="ErrorDetails">Error details if search failed.</param>
public record SemanticSearchResult(
    bool Success,
    IEnumerable<SearchResult> Results,
    int TotalMatches,
    long SearchTimeMs,
    string QueryProcessed,
    string? ErrorDetails = null
);

/// <summary>
/// Result of code pattern analysis operations.
/// </summary>
/// <param name="Success">Whether the analysis succeeded.</param>
/// <param name="Patterns">Patterns found in the code.</param>
/// <param name="Suggestions">Improvement suggestions.</param>
/// <param name="ConfidenceScores">Confidence scores for patterns.</param>
/// <param name="AnalysisTimeMs">Time taken for analysis.</param>
/// <param name="ErrorDetails">Error details if analysis failed.</param>
public record CodePatternAnalysisResult(
    bool Success,
    IEnumerable<CodePattern> Patterns,
    IEnumerable<ImprovementSuggestion> Suggestions,
    Dictionary<string, double> ConfidenceScores,
    long AnalysisTimeMs,
    string? ErrorDetails = null
);

/// <summary>
/// Result of knowledge base operations.
/// </summary>
/// <param name="Success">Whether the operation succeeded.</param>
/// <param name="OperationResult">Result of the knowledge base operation.</param>
/// <param name="EntitiesAffected">Number of entities affected.</param>
/// <param name="OperationTimeMs">Time taken for the operation.</param>
/// <param name="ErrorDetails">Error details if operation failed.</param>
public record KnowledgeBaseResult(
    bool Success,
    KnowledgeBaseOperationResult OperationResult,
    int EntitiesAffected,
    long OperationTimeMs,
    string? ErrorDetails = null
);

/// <summary>
/// Result of RAG query operations.
/// </summary>
/// <param name="Success">Whether the query succeeded.</param>
/// <param name="Answer">Answer generated by the RAG system.</param>
/// <param name="Sources">Sources used to generate the answer.</param>
/// <param name="Confidence">Confidence in the answer (0.0-1.0).</param>
/// <param name="TokensUsed">Number of tokens used in generation.</param>
/// <param name="GenerationTimeMs">Time taken for generation.</param>
/// <param name="ErrorDetails">Error details if query failed.</param>
public record RagQueryResult(
    bool Success,
    string Answer,
    IEnumerable<RagSource> Sources,
    double Confidence,
    int TokensUsed,
    long GenerationTimeMs,
    string? ErrorDetails = null
);

/// <summary>
/// A search result from semantic search.
/// </summary>
/// <param name="Id">Unique identifier for the result.</param>
/// <param name="Content">Content of the search result.</param>
/// <param name="Similarity">Similarity score (0.0-1.0).</param>
/// <param name="Source">Source of the result.</param>
/// <param name="Metadata">Additional metadata.</param>
/// <param name="Location">Location of the result in the codebase.</param>
public record SearchResult(
    string Id,
    string Content,
    double Similarity,
    string Source,
    Dictionary<string, object> Metadata,
    SourceLocation Location
);

/// <summary>
/// A code pattern found in analysis.
/// </summary>
/// <param name="Id">Unique identifier for the pattern.</param>
/// <param name="PatternType">Type of the pattern.</param>
/// <param name="Description">Description of the pattern.</param>
/// <param name="CodeSnippet">Code snippet containing the pattern.</param>
/// <param name="Confidence">Confidence in the pattern (0.0-1.0).</param>
/// <param name="Location">Location of the pattern in the code.</param>
/// <param name="Metadata">Additional metadata about the pattern.</param>
public record CodePattern(
    string Id,
    string PatternType,
    string Description,
    string CodeSnippet,
    double Confidence,
    SourceLocation Location,
    Dictionary<string, object> Metadata
);

/// <summary>
/// An improvement suggestion for code.
/// </summary>
/// <param name="Id">Unique identifier for the suggestion.</param>
/// <param name="SuggestionType">Type of suggestion.</param>
/// <param name="Description">Description of the suggestion.</param>
/// <param name="CodeExample">Example code showing the improvement.</param>
/// <param name="Confidence">Confidence in the suggestion (0.0-1.0).</param>
/// <param name="Effort">Estimated effort to implement.</param>
/// <param name="Benefits">Benefits of implementing the suggestion.</param>
public record ImprovementSuggestion(
    string Id,
    string SuggestionType,
    string Description,
    string? CodeExample,
    double Confidence,
    string Effort,
    IEnumerable<string> Benefits
);

/// <summary>
/// Result of a knowledge base operation.
/// </summary>
/// <param name="OperationType">Type of operation performed.</param>
/// <param name="EntityId">ID of the entity operated on.</param>
/// <param name="EntityType">Type of the entity.</param>
/// <param name="Changes">Changes made to the entity.</param>
/// <param name="Timestamp">When the operation was performed.</param>
public record KnowledgeBaseOperationResult(
    string OperationType,
    string EntityId,
    string EntityType,
    Dictionary<string, object> Changes,
    DateTime Timestamp
);

/// <summary>
/// A source used by the RAG system.
/// </summary>
/// <param name="Id">Unique identifier for the source.</param>
/// <param name="SourceType">Type of the source.</param>
/// <param name="Content">Content from the source.</param>
/// <param name="Relevance">Relevance to the query (0.0-1.0).</param>
/// <param name="Location">Location of the source.</param>
/// <param name="Metadata">Additional metadata about the source.</param>
public record RagSource(
    string Id,
    string SourceType,
    string Content,
    double Relevance,
    SourceLocation Location,
    Dictionary<string, object> Metadata
);

/// <summary>
/// Configuration for the Knowledge RAG service.
/// </summary>
/// <param name="VectorStoreConfig">Configuration for the vector store.</param>
/// <param name="EmbeddingConfig">Configuration for embeddings.</param>
/// <param name="RagConfig">Configuration for RAG operations.</param>
/// <param name="IndexingConfig">Configuration for indexing operations.</param>
/// <param name="Version">Version of the configuration.</param>
/// <param name="LastUpdated">When the configuration was last updated.</param>
public record KnowledgeRagConfiguration(
    VectorStoreConfiguration VectorStoreConfig,
    EmbeddingConfiguration EmbeddingConfig,
    RagConfiguration RagConfig,
    IndexingConfiguration IndexingConfig,
    string Version,
    DateTime LastUpdated
);

/// <summary>
/// Configuration for the vector store.
/// </summary>
/// <param name="Provider">Vector store provider.</param>
/// <param name="ConnectionString">Connection string for the vector store.</param>
/// <param name="IndexName">Name of the index.</param>
/// <param name="Dimensions">Number of dimensions for vectors.</param>
/// <param name="SimilarityMetric">Similarity metric to use.</param>
public record VectorStoreConfiguration(
    string Provider,
    string ConnectionString,
    string IndexName,
    int Dimensions,
    string SimilarityMetric
);

/// <summary>
/// Configuration for embeddings.
/// </summary>
/// <param name="Provider">Embedding provider.</param>
/// <param name="Model">Model to use for embeddings.</param>
/// <param name="MaxTokens">Maximum tokens per embedding.</param>
/// <param name="BatchSize">Batch size for embedding operations.</param>
public record EmbeddingConfiguration(
    string Provider,
    string Model,
    int MaxTokens,
    int BatchSize
);

/// <summary>
/// Configuration for RAG operations.
/// </summary>
/// <param name="MaxContextLength">Maximum context length for queries.</param>
/// <param name="Temperature">Temperature for response generation.</param>
/// <param name="MaxTokens">Maximum tokens in responses.</param>
/// <param name="TopK">Number of top results to consider.</param>
/// <param name="SimilarityThreshold">Minimum similarity threshold.</param>
public record RagConfiguration(
    int MaxContextLength,
    double Temperature,
    int MaxTokens,
    int TopK,
    double SimilarityThreshold
);

/// <summary>
/// Configuration for indexing operations.
/// </summary>
/// <param name="ChunkSize">Size of text chunks for indexing.</param>
/// <param name="ChunkOverlap">Overlap between chunks.</param>
/// <param name="IndexingBatchSize">Batch size for indexing operations.</param>
/// <param name="UpdateFrequency">How often to update the index.</param>
public record IndexingConfiguration(
    int ChunkSize,
    int ChunkOverlap,
    int IndexingBatchSize,
    TimeSpan UpdateFrequency
);