namespace IndFusion.Mcp.Core.Abstractions;

/// <summary>
/// Result of RAG query operations.
/// </summary>
/// <param name="Success">Whether the query succeeded.</param>
/// <param name="Answer">Answer generated by the RAG system.</param>
/// <param name="Sources">Sources used to generate the answer.</param>
/// <param name="Confidence">Confidence in the answer (0.0-1.0).</param>
/// <param name="TokensUsed">Number of tokens used in generation.</param>
/// <param name="GenerationTimeMs">Time taken for generation.</param>
/// <param name="ErrorDetails">Error details if query failed.</param>
public record RagQueryResult(
    bool Success,
    string Answer,
    IEnumerable<RagSource> Sources,
    double Confidence,
    int TokensUsed,
    long GenerationTimeMs,
    string? ErrorDetails = null
);