classDiagram

	class GatewayTasksCreateBarCodeAsyncTests  {
		-IIndTraceControllerRx _controllerMock
		-IGatewayCommandDispatcher _guiCommandDispatcherMock
		-IHubConnection? _hubConnectionMock
		-CancellationToken _cancellationToken
		+CreateBarCodeAsync_ShouldReturnLabel_WhenCommandSucceeds() Task
		+CreateBarCodeAsync_ShouldLogError_WhenCommandFails() Task
		+CreateBarCodeAsync_ShouldReturnValidResult_WhenCalled() Task
	}
	class HubFactoryHelper  {
		+IHubConnectionFactory connectionFactory
	}
	class NonParallelCollectionDefinition  {
	}
	class SimulatedCommandTests  {
		+ParseCommand_ShouldReturnCorrectSimulatedCommand_WhenValidCommandIsGiven() void
		+ParseCommand_ShouldNotReturnACommand_WhenInvalidCommandIsGiven() void
		+ParseCommand_NonReturnACommand_WhenNonIntegerValuesAreGivenInIntegerFields() void
	}
	class GatewayTasksReadBarCodeAsyncTests  {
		-IIndTraceControllerRx _controllerMock
		-IGatewayCommandDispatcher _guiCommandDispatcherMock
		-IHubConnection? _hubConnectionMock
		-CancellationToken _cancellationToken
		+ReadBarCodeAsync_ShouldReturnBarCodeDetail_WhenCommandSucceeds() Task
		+ReadBarCodeAsync_ShouldLogError_WhenCommandFails() Task
	}
	class GatewayTasksUpdateCycleAsyncTests  {
		-IIndTraceControllerRx _controllerMock
		-IGatewayCommandDispatcher _guiCommandDispatcherMock
		-IHubConnection? _hubConnectionMock
		-CancellationToken _cancellationToken
		+UpdateCycleAsync_ShouldReturnBarCodeDetail_WhenCommandSucceeds() Task
		+UpdateCycleAsync_ShouldLogError_WhenCommandFails() Task
	}
	class GatewayTasksEndOfProcessAsyncTests  {
		-IIndTraceControllerRx _controllerMock
		-IGatewayCommandDispatcher _guiCommandDispatcherMock
		-IHubConnection? _hubConnectionMock
		-CancellationToken _cancellationToken
		+EndOfProcessAsync_ShouldLogError_WhenCommandFails() Task
		+EndOfProcessAsync_ShouldReturnBarCodeDetail_WhenCommandSucceeds() Task
	}
	class GatewayTasksCreateCyclesCommandTests  {
		-IIndTraceControllerRx _controllerMock
		-IGatewayCommandDispatcher _guiCommandDispatcherMock
		-IHubConnection? _hubConnectionMock
		-CancellationToken _cancellationToken
		+CreateCycleAsync_ShouldReturnBarCodeDetail_WhenCommandSucceeds() Task
		+CreateCycleAsync_ShouldLogError_WhenCommandFails() Task
	}
	class SelfRegisteredExtensions  {
		+AddSelfRegisteredExtensions(global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder, string[] args) void
	}
	class XunitAutoGeneratedEntryPoint  {
		+Main(string[] args) int
	}

	GatewayTasksCreateBarCodeAsyncTests --|> HubFactoryHelper
	GatewayTasksReadBarCodeAsyncTests --|> HubFactoryHelper
	GatewayTasksUpdateCycleAsyncTests --|> HubFactoryHelper
	GatewayTasksEndOfProcessAsyncTests --|> HubFactoryHelper
	GatewayTasksCreateCyclesCommandTests --|> HubFactoryHelper
