using IndFusion.Analyzer.Tests.Testing;
using IndFusion.Analyzers.Testing;
using Microsoft.CodeAnalysis;
using Shouldly;
using Xunit;

namespace IndFusion.Analyzer.Tests.TestCases;

/// <summary>
/// Regression tests for EXXER101 false-positive mitigations.
/// </summary>
public class UseXUnitV3AnalyzerFalsePositiveTests
{
    [Fact]
    public void Should_Not_Report_For_AutoGenerated_TestingPlatform_Shims()
    {
        const string testCode = @"\
// <auto-generated>\
using Microsoft.Testing.Platform;\
\
[assembly: Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook]\
namespace Generated { }";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(
            testCode,
            new UseXUnitV3Analyzer(),
            filePath: @"C:\\repo\\Tests\\obj\\Debug\\net10.0\\SelfRegisteredExtensions.g.cs");

        diagnostics.ShouldBeEmpty();
    }

    [Fact]
    public void Should_Not_Report_For_TestingPlatform_BuilderHooks()
    {
        const string testCode = @"\
using Microsoft.Testing.Platform.MSBuild;\
\
[TestingPlatformBuilderHook]\
public static class Hook { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Respect_AnalyzerConfig_Ignore_List()
    {
        const string testCode = @"\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class LegacyTests\
{\
\t[TestMethod] public void Should_Work() { }\
}";

        var options = AnalyzerOptionsFactory.Create(
            ("dotnet_diagnostic.EXXER101.ignore_projects", "IndFusion.Analyzer.Tests"),
            ("dotnet_diagnostic.EXXER101.project_name", "IndFusion.Analyzer.Tests"));

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Not_Report_For_Local_Wrapper_Attributes()
    {
        const string testCode = @"\
namespace Compat\
{\
\tpublic class TestMethodAttribute : System.Attribute { }\
}\
\
[Compat.TestMethod]\
public class Sample { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Not_Report_For_TestingPlatform_Using()
    {
        const string testCode = @"\
using Microsoft.Testing.Platform.Builder;\
\
public static class Boot { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Not_Report_For_Sample_Code_In_Strings()
    {
        const string testCode = @"\
public sealed class Docs\
{\
\tpublic const string Sample = \"[TestMethod] public void Legacy() { }\";\
}";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Honor_SuppressTestFrameworkConversion_Attribute()
    {
        const string testCode = @"\
[assembly: SuppressTestFrameworkConversion(\"MSTestLegacy\")]\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { [TestMethod] public void Old() { } }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Not_Report_For_Analyzer_TestCases_Project()
    {
        const string testCode = @"\
using NUnit.Framework;\
\
[TestFixture]\
public class AnalyzerFixture { }";

        var options = AnalyzerOptionsFactory.Create(("dotnet_diagnostic.EXXER101.project_name", "IndFusion.Analyzer.Tests"));
        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options).ShouldBeEmpty();
    }

    [Fact]
    public void Should_Report_GlobalUsing_Only_Once()
    {
        const string testCode = @"\
global using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { }";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer());
        diagnostics.Count(d => d.Id == DiagnosticIds.UseXUnitV3).ShouldBe(1);
    }

    [Fact]
    public void Should_Respect_Severity_From_EditorConfig()
    {
        const string testCode = @"\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { }";

        var options = AnalyzerOptionsFactory.Create(("dotnet_diagnostic.EXXER101.severity", "suggestion"));
        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options);
        diagnostics.Single().Severity.ShouldBe(DiagnosticSeverity.Info);
    }
}


