// file: test/IndFusion.Analyzer.Tests/TestCases/UseXUnitV3AnalyzerFalsePositiveTests.cs

using IndFusion.Analyzer.Testing;
using IndFusion.Analyzer.Tests.Testing;
using Microsoft.CodeAnalysis;
using Shouldly;
using Xunit;

namespace IndFusion.Analyzer.Tests.TestCases;

/// <summary>
/// Regression tests for EXXER101 false-positive mitigations.
/// </summary>
public class UseXUnitV3AnalyzerFalsePositiveTests
{
    /// <summary>
    /// Verifies that the analyzer does not report diagnostics for auto-generated shims created by the testing platform.
    /// </summary>
    /// <remarks>This test ensures that files marked as auto-generated and containing platform-specific shims
    /// are excluded from analyzer reporting. It is intended to prevent false positives in generated code
    /// scenarios.</remarks>
    [Fact]
    public void Should_Not_Report_For_AutoGenerated_TestingPlatform_Shims()
    {
        const string testCode = @"\
// <auto-generated>\
using Microsoft.Testing.Platform;\
\
[assembly: Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook]\
namespace Generated { }";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(
            testCode,
            new UseXUnitV3Analyzer(),
            filePath: @"C:\\repo\\Tests\\obj\\Debug\\net10.0\\SelfRegisteredExtensions.g.cs");

        diagnostics.ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer does not report diagnostics for classes marked with the TestingPlatformBuilderHook
    /// attribute.
    /// </summary>
    /// <remarks>This test ensures compatibility with the Microsoft.Testing.Platform.MSBuild infrastructure by
    /// confirming that builder hooks are not incorrectly flagged by the UseXUnitV3Analyzer.</remarks>
    [Fact]
    public void Should_Not_Report_For_TestingPlatform_BuilderHooks()
    {
        const string testCode = @"\
using Microsoft.Testing.Platform.MSBuild;\
\
[TestingPlatformBuilderHook]\
public static class Hook { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer correctly ignores projects specified in the analyzer configuration ignore list.
    /// </summary>
    /// <remarks>This test ensures that when a project is listed in the
    /// 'dotnet_diagnostic.EXXER101.ignore_projects' configuration, the analyzer does not report diagnostics for that
    /// project. Use this test to confirm compliance with analyzer configuration settings related to project
    /// exclusion.</remarks>
    [Fact]
    public void Should_Respect_AnalyzerConfig_Ignore_List()
    {
        const string testCode = @"\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class LegacyTests\
{\
\t[TestMethod] public void Should_Work() { }\
}";

        var options = AnalyzerOptionsFactory.Create(
            ("dotnet_diagnostic.EXXER101.ignore_projects", "IndFusion.Analyzer.Tests"),
            ("dotnet_diagnostic.EXXER101.project_name", "IndFusion.Analyzer.Tests"));

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer does not report diagnostics for attributes defined locally as wrappers, such as
    /// custom attributes mimicking xUnit attributes.
    /// </summary>
    /// <remarks>This test ensures that the analyzer correctly ignores locally defined wrapper attributes and
    /// does not produce false positives when such attributes are used. It is intended to validate compatibility
    /// scenarios where custom attributes may resemble those from external libraries.</remarks>
    [Fact]
    public void Should_Not_Report_For_Local_Wrapper_Attributes()
    {
        const string testCode = @"\
namespace Compat\
{\
\tpublic class TestMethodAttribute : System.Attribute { }\
}\
\
[Compat.TestMethod]\
public class Sample { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer does not report diagnostics when code uses the Microsoft.Testing.Platform.Builder
    /// namespace.
    /// </summary>
    /// <remarks>This test ensures compatibility with the Microsoft.Testing.Platform.Builder API by confirming
    /// that no issues are flagged by the UseXUnitV3Analyzer. Use this test to validate that analyzer rules do not
    /// incorrectly target code intended for the Testing Platform.</remarks>
    [Fact]
    public void Should_Not_Report_For_TestingPlatform_Using()
    {
        const string testCode = @"\
using Microsoft.Testing.Platform.Builder;\
\
public static class Boot { }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that sample code contained within string literals does not trigger reporting or analysis.
    /// </summary>
    /// <remarks>Use this test to ensure that code analysis tools or reporting mechanisms correctly ignore
    /// code samples embedded in strings, such as documentation or example code, and do not produce false
    /// positives.</remarks>
    [Fact]
    public void Should_Not_Report_For_Sample_Code_In_Strings()
    {
        const string testCode = @"\
public sealed class Docs\
{\
\tpublic const string Sample = ""[TestMethod] public void Legacy() { }""; \
}";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the SuppressTestFrameworkConversion attribute prevents automatic conversion of MSTestLegacy tests
    /// to another test framework.
    /// </summary>
    /// <remarks>Use this test to ensure that applying the SuppressTestFrameworkConversion attribute to an
    /// assembly correctly suppresses test framework conversion behavior. This is relevant when maintaining
    /// compatibility with legacy MSTest tests or when conversion is not desired.</remarks>
    [Fact]
    public void Should_Honor_SuppressTestFrameworkConversion_Attribute()
    {
        const string testCode = @"\
[assembly: SuppressTestFrameworkConversion(""MSTestLegacy"")]\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { [TestMethod] public void Old() { } }";

        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer()).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer does not report diagnostics for projects identified as analyzer test cases.
    /// </summary>
    /// <remarks>Use this method to ensure that the analyzer correctly ignores projects with the name
    /// 'IndFusion.Analyzer.Tests', as specified by the analyzer options. This is typically used to prevent false positives
    /// when running analyzers on their own test projects.</remarks>
    [Fact]
    public void Should_Not_Report_For_Analyzer_TestCases_Project()
    {
        const string testCode = @"\
using NUnit.Framework;\
\
[TestFixture]\
public class AnalyzerFixture { }";

        var options = AnalyzerOptionsFactory.Create(("dotnet_diagnostic.EXXER101.project_name", "IndFusion.Analyzer.Tests"));
        AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options).ShouldBeEmpty();
    }

    /// <summary>
    /// Verifies that the analyzer reports a diagnostic only once for global using directives.
    /// </summary>
    [Fact]
    public void Should_Report_GlobalUsing_Only_Once()
    {
        const string testCode = @"\
global using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { }";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer());
        diagnostics.Count(d => d.Id == DiagnosticIds.UseXUnitV3).ShouldBe(1);
    }

    /// <summary>
    /// Verifies that the analyzer respects the severity level specified in the EditorConfig for the EXXER101
    /// diagnostic.
    /// </summary>
    /// <remarks>This test ensures that when the severity for EXXER101 is set to 'suggestion' in EditorConfig,
    /// the analyzer reports the diagnostic with the corresponding severity. Use this test to confirm correct
    /// integration between EditorConfig settings and analyzer behavior.</remarks>
    [Fact]
    public void Should_Respect_Severity_From_EditorConfig()
    {
        const string testCode = @"\
using Microsoft.VisualStudio.TestTools.UnitTesting;\
\
[TestClass]\
public class Legacy { }";

        var options = AnalyzerOptionsFactory.Create(("dotnet_diagnostic.EXXER101.severity", "suggestion"));
        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new UseXUnitV3Analyzer(), analyzerOptions: options);
        diagnostics.Single().Severity.ShouldBe(DiagnosticSeverity.Info);
    }
}