classDiagram

	class FakeHttpMessageHandler  {
		-SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) Task~HttpResponseMessage~
	}
	class ReactiveEventServiceTests  {
		-ILogger logger
		-KpiDataSink kpiDataPort
		-ISender sender
		+int portToCheck
		+ ShouldSkipThisClass : bool
		+ProcessOeeRegisterAsync_ShouldEmitDto_AndCallKpiDataPort() Task
		+ProcessOeeRegisterAsync_ShouldNotifyObservers_WhenValidOeeIsComputed() Task
		+ProcessOeeRegisterAsync_ShouldNotNotifyObserver_WhenOeeCalculationFails() Task
		+ProcessOeeRegisterAsync_ShouldNotEmit_WhenInvalidDataProvided() Task
	}
	class PlcManagerTests  {
		+InitializeAsync_ShouldReturnSuccess_WhenAllPlcsHavePerformanceTags() Task
		+InitializeAsync_ShouldReturnFailure_WhenPlcHasNoPerformanceTags() Task
		+InitializeAsync_ShouldThrow_WhenNoPlcIsOeeEnabled() Task
		+InitializeAsync_ShouldLogError_WhenPlcHasNoTags() Task
	}
	class PortChecker  {
		+IsPortClosed(int port) bool
	}
	class PlcProcessorTests  {
		-IPlc _controller
		-ILogger _logger
		-PlcData _plcData
		-Dictionary~string&#44&#32VariableS7~ _variables
		-PlcProcessor _processor
		-BehaviorSubject~ConnectionState~ _connectionState
		+ConnectWithNotificationAsync_Should_ConnectSuccessfully() Task
		+ConnectWithNotificationAsync_Should_Timeout() Task
		+ReadPerformanceDataFromPlcAsync_Should_ReturnValidData() Task
		+ReadPerformanceDataFromPlcAsync_Should_Return_ValidResults() Task
	}
	class RepoPlcServiceTests  {
		-ITagsRepository _tagsRepo
		-ILogger~RepoPlcService~ _logger
		-RepoPlcService _sut
		+LoadPlcsAsync_Should_Return_Success_When_PLCs_Found() Task
		+LoadPlcsAsync_Should_Return_Failure_When_Empty() Task
		+LoadTagsAsync_Should_Return_Success_When_Tags_Found() Task
		+LoadTagsAsync_Should_Return_Failure_When_Empty() Task
		+LogPlcsAndTags_Should_Log_Correct_Info() void
	}
	class PlcDbTagsRepositoryIntegrationTests  {
		-string ConnectionString
		-SqlConnection _connection
		-PlcDbTagsRepository _repository
		-ILogger~PlcDbTagsRepository~ _logger
		-ITestOutputHelper output
		+InitializeAsync() ValueTask
		+DisposeAsync() ValueTask
		+GetPlcsAsync_ShouldReturnPlcData() Task
		+GetPlcsAsync_ShouldReturnCompleteDataForPLC100PlcData() Task
		+GetDistinctDbInfosAsync_ShouldReturnDbList() Task
		+GetTagsGroupedByMachineAsync_NoArgs_ShouldReturnDictionary() Task
		+GetTagsAsync_WithMachineId_ShouldReturnDictionary() Task
		+GetTagsAsync_WithMachineId_ShouldReturnDictionaryAndHaveMembers() Task
		+GetTagsAsync_WithMachineId100_ShouldReturnDictionaryAndHaveMembers() Task
	}
	class SelfRegisteredExtensions  {
		+AddSelfRegisteredExtensions(global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder, string[] args) void
	}
	class XunitAutoGeneratedEntryPoint  {
		+Main(string[] args) int
	}

	FakeHttpMessageHandler --|> HttpMessageHandler
	PlcDbTagsRepositoryIntegrationTests --|> IAsyncLifetime
