using IndFusion.Analyzer.CodeFormatting;
using IndFusion.Analyzer.Tests.Testing;
using Shouldly;
using Xunit;

namespace IndFusion.Analyzer.Tests.TestCases.CodeFormatting;

/// <summary>
/// Tests for EXXER900 - ProjectFormatting Analyzer false-positive scenarios.
/// </summary>
public class ProjectFormattingFalsePositiveTests
{
    //  Story 1.1: Exempt Generated Files

    /// <summary>
    /// Tests that generated files are exempted from project formatting diagnostics.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Generated_Files()
    {
        const string testCode = @"
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

namespace MyProject.Generated
{
    public class GeneratedClass
    {
        public void GeneratedMethod()
        {
            // Generated code content
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.2: Exempt Empty or Whitespace-Only Files

    /// <summary>
    /// Tests that empty or whitespace-only files are exempted from project formatting diagnostics.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Empty_Or_Whitespace_Only_Files()
    {
        const string testCode = @"
// This file contains only comments and whitespace

// Another comment

";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.3: Anchor Diagnostic to Start of File

    /// <summary>
    /// Tests that the diagnostic is anchored to the start of the file.
    /// </summary>
    [Fact]
    public void Should_Anchor_Diagnostic_To_Start_Of_File()
    {
        const string testCode = @"
using System;

namespace MyProject
{
    public class TestClass
    {
        public void TestMethod()
        {
            Console.WriteLine(""Hello World"");
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        var diagnostic = diagnostics[0];
        var location = diagnostic.Location;
        var span = location.SourceSpan;
        
        // Diagnostic should be at the very beginning of the file (span 0, length 0)
        span.Start.ShouldBe(0);
        span.Length.ShouldBe(0);
    }

     // 

    //  Story 1.4: Correctly Handle LINQ Assignments

    /// <summary>
    /// Tests that LINQ assignments are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_LINQ_Assignments_Correctly()
    {
        const string testCode = @"
using System.Linq;

namespace MyProject
{
    public class LinqExample
    {
        public void ProcessData()
        {
            var numbers = new[] { 1, 2, 3, 4, 5 };
            var result = numbers.Where(x => x > 2).Select(x => x * 2).ToList();
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle LINQ correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 

    //  Story 1.5: Correctly Handle Awaited Assignments

    /// <summary>
    /// Tests that awaited assignments are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_Awaited_Assignments_Correctly()
    {
        const string testCode = @"
using System.Threading.Tasks;

namespace MyProject
{
    public class AsyncExample
    {
        public async Task ProcessAsync()
        {
            var result = await SomeAsyncMethod();
            var data = await GetDataAsync();
        }

        private async Task<string> SomeAsyncMethod() => await Task.FromResult(""test"");
        private async Task<int> GetDataAsync() => await Task.FromResult(42);
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle async correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 

    //  Story 1.6: Correctly Handle Object and Dictionary Initializers

    /// <summary>
    /// Tests that object and dictionary initializers are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_Object_And_Dictionary_Initializers_Correctly()
    {
        const string testCode = @"
using System.Collections.Generic;

namespace MyProject
{
    public class InitializerExample
    {
        public void CreateObjects()
        {
            var person = new Person
            {
                Name = ""John"",
                Age = 30
            };

            var dictionary = new Dictionary<string, int>
            {
                { ""key1"", 1 },
                { ""key2"", 2 }
            };
        }
    }

    public class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle initializers correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 

    //  Story 1.7: Correctly Handle Fluent ToDictionary Pipelines

    /// <summary>
    /// Tests that fluent ToDictionary pipelines are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_Fluent_ToDictionary_Pipelines_Correctly()
    {
        const string testCode = @"
using System.Linq;

namespace MyProject
{
    public class FluentPipelineExample
    {
        public void ProcessData()
        {
            var numbers = new[] { 1, 2, 3, 4, 5 };
            var result = numbers
                .Where(x => x > 2)
                .Select(x => new { Key = x.ToString(), Value = x * 2 })
                .ToDictionary(x => x.Key, x => x.Value);
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle fluent pipelines correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 

    //  Story 1.8: Correctly Handle Specification Builder Assignments

    /// <summary>
    /// Tests that specification builder assignments are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_Specification_Builder_Assignments_Correctly()
    {
        const string testCode = @"
namespace MyProject
{
    public class SpecificationExample
    {
        public void CreateSpecification()
        {
            var spec = new Specification<Person>(p => p.Age > 18);
            var complexSpec = new Specification<Person>(p => p.Name != null && p.Age > 21);
        }
    }

    public class Specification<T>
    {
        public Specification(System.Func<T, bool> predicate)
        {
            Predicate = predicate;
        }

        public System.Func<T, bool> Predicate { get; }
    }

    public class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle specifications correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 

    //  Story 1.9: Correctly Handle Fluent Result Pipelines

    /// <summary>
    /// Tests that fluent Result pipelines are handled correctly.
    /// </summary>
    [Fact]
    public void Should_Handle_Fluent_Result_Pipelines_Correctly()
    {
        const string testCode = @"
using System.Threading.Tasks;

namespace MyProject
{
    public class ResultPipelineExample
    {
        public async Task ProcessResult()
        {
            var result = await Result.Success(""data"")
                .Map(x => x.ToUpper())
                .Bind(x => Result.Success(x + ""_processed""));
        }
    }

    public class Result<T>
    {
        public static Result<T> Success(T value) => new Result<T>(value);
        public Result<T> Map<U>(System.Func<T, U> mapper) => new Result<U>(mapper(Value));
        public Result<U> Bind<U>(System.Func<T, Result<U>> binder) => binder(Value);
        private Result(T value) => Value = value;
        public T Value { get; }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new ProjectFormattingAnalyzer());
        diagnostics.ShouldHaveSingleItem();
        
        // Should still report the diagnostic but handle Result pipelines correctly
        var diagnostic = diagnostics[0];
        diagnostic.Id.ShouldBe(DiagnosticIds.ProjectFormatting);
    }

     // 
}
