using System;
using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace IndFusion.Analyzers.Testing;

/// <summary>
/// Analyzer that enforces XUnit v3 usage for testing.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class UseXUnitV3Analyzer : DiagnosticAnalyzer
{
    /// <summary>
    /// Gets the localized analyzer title shown when an outdated testing attribute is discovered.
    /// </summary>
    private static readonly LocalizableString Title = "Use XUnit v3 for testing";

    /// <summary>
    /// Gets the format string used for diagnostics describing the discovered testing framework.
    /// </summary>
    private static readonly LocalizableString MessageFormat = "Use XUnit v3 instead of '{0}' for testing";

    /// <summary>
    /// Gets the diagnostic description explaining why XUnit v3 should be preferred.
    /// </summary>
    private static readonly LocalizableString Description = "XUnit v3 should be used for all testing instead of other testing frameworks like MSTest or NUnit.";

    /// <summary>
    /// The diagnostic emitted when MSTest or NUnit artifacts are found in source code.
    /// </summary>
    private static readonly DiagnosticDescriptor Rule = new(
        DiagnosticIds.UseXUnitV3,
        Title,
        MessageFormat,
        DiagnosticCategories.Testing,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: Description);

    /// <summary>
    /// Gets the diagnostics supported by this analyzer.
    /// </summary>
    /// <value>An immutable array containing the single <c>UseXUnitV3</c> descriptor.</value>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Rule);

    /// <summary>
    /// Configures syntax node actions used to flag legacy testing frameworks.
    /// </summary>
    /// <param name="context">The analysis context used to register callbacks.</param>
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(AnalyzeAttribute, SyntaxKind.Attribute);
        context.RegisterSyntaxNodeAction(AnalyzeUsingDirective, SyntaxKind.UsingDirective);
    }

    /// <summary>
    /// Examines attribute declarations for MSTest or NUnit usage and reports diagnostics when found.
    /// </summary>
    /// <param name="context">The syntax node analysis context for the attribute.</param>
    private static void AnalyzeAttribute(SyntaxNodeAnalysisContext context)
    {
        var attribute = (AttributeSyntax)context.Node;
        if (IsIgnoredByProjectConfig(context)) return;
        if (IsAutoGenerated(context.Node.SyntaxTree) || IsInBuildOutputFolder(context.Node.SyntaxTree.FilePath)) return;
        if (HasAssemblySuppression(context)) return;

        var attributeName = attribute.Name.ToString();

        // Allow Microsoft Testing Platform attributes and local wrappers
        var attributeSymbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
        var attrTypeName = attributeSymbol?.ContainingType?.ToDisplayString() ?? attributeName;
        if (IsTestingPlatform(attrTypeName)) return;
        if (attributeSymbol?.ContainingType != null && attributeSymbol.ContainingType.Locations.Any(l => l.IsInSource)) return;

        // Check for forbidden testing framework attributes
        var forbiddenAttributes = new[]
        {
            "TestMethod",
            "TestClass",
            "TestInitialize",
            "TestCleanup",
            "ClassInitialize",
            "ClassCleanup",
            "AssemblyInitialize",
            "AssemblyCleanup",
            "Test",
            "TestCase",
            "TestFixture",
            "SetUp",
            "TearDown",
            "OneTimeSetUp",
            "OneTimeTearDown",
            "TestFixtureSetUp",
            "TestFixtureTearDown"
        };

        foreach (var forbidden in forbiddenAttributes)
        {
            if (attributeName == forbidden || attributeName.EndsWith("." + forbidden))
            {
                // Check namespace if attribute has a qualifier (e.g., "Compat.TestMethod")
                if (attributeName.Contains("."))
                {
                    // If we have semantic info, use it for accurate checking
                    if (attributeSymbol?.ContainingType != null)
                    {
                        var namespaceName = attributeSymbol.ContainingType.ContainingNamespace?.ToDisplayString();
                        if (namespaceName != null)
                        {
                            var isKnownFramework = 
                                namespaceName.StartsWith("Microsoft.VisualStudio.TestTools.UnitTesting") ||
                                namespaceName.StartsWith("NUnit.Framework");
                            
                            if (!isKnownFramework)
                            {
                                // This is a local/custom attribute with a similar name, skip it
                                continue;
                            }
                        }
                    }
                    else
                    {
                        // Fallback: check if the attribute name starts with a known framework namespace prefix
                        var isKnownFramework = 
                            attributeName.StartsWith("Microsoft.VisualStudio.TestTools.UnitTesting.") ||
                            attributeName.StartsWith("NUnit.Framework.");
                        
                        if (!isKnownFramework)
                        {
                            // Likely a local/custom attribute, skip it
                            continue;
                        }
                    }
                }
                
                var framework = GetFrameworkName(forbidden);
                var descriptor = GetDescriptorWithSeverity(context) ?? Rule;
                var diagnostic = Diagnostic.Create(
                    descriptor,
                    attribute.GetLocation(),
                    framework);

                context.ReportDiagnostic(diagnostic);
                break;
            }
        }
    }

    /// <summary>
    /// Inspects using directives for forbidden testing framework namespaces.
    /// </summary>
    /// <param name="context">The syntax node analysis context for the using directive.</param>
    private static void AnalyzeUsingDirective(SyntaxNodeAnalysisContext context)
    {
        var usingDirective = (UsingDirectiveSyntax)context.Node;
        if (IsIgnoredByProjectConfig(context)) return;
        if (IsAutoGenerated(context.Node.SyntaxTree) || IsInBuildOutputFolder(context.Node.SyntaxTree.FilePath)) return;

        var namespaceName = usingDirective.Name?.ToString();

        if (namespaceName == null)
        {
            return;
        }

        // Allow current Xunit usage (this is effectively XUnit v3 or the current version)
        if (namespaceName == "Xunit")
        {
            return; // Don't report diagnostic for current Xunit usage
        }

        // Allow Microsoft Testing Platform namespaces
        if (IsTestingPlatform(namespaceName))
        {
            return;
        }

        // Check for other forbidden testing framework namespaces
        var forbiddenNamespaces = new[]
        {
            "Microsoft.VisualStudio.TestTools.UnitTesting",
            "NUnit.Framework",
            "NUnit"
        };

        foreach (var forbidden in forbiddenNamespaces)
        {
            if (namespaceName == forbidden || namespaceName.StartsWith(forbidden + "."))
            {
                // Deduplicate per tree per offending namespace (avoid double-reporting global usings)
                if (!ShouldReportUsing(context.Node.SyntaxTree, namespaceName)) return;

                var framework = GetFrameworkNameFromNamespace(forbidden);
                var descriptor = GetDescriptorWithSeverity(context) ?? Rule;
                var diagnostic = Diagnostic.Create(
                    descriptor,
                    usingDirective.GetLocation(),
                    framework);

                context.ReportDiagnostic(diagnostic);
                break;
            }
        }
    }

    /// <summary>
    /// Maps a forbidden attribute name to its parent testing framework.
    /// </summary>
    /// <param name="attributeName">The attribute identifier discovered in source.</param>
    /// <returns>The friendly testing framework name associated with the attribute.</returns>
    private static string GetFrameworkName(string attributeName) => attributeName switch
    {
        "TestMethod" or "TestClass" or "TestInitialize" or "TestCleanup" or
        "ClassInitialize" or "ClassCleanup" or "AssemblyInitialize" or "AssemblyCleanup" => "MSTest",
        "Test" or "TestCase" or "TestFixture" or "SetUp" or "TearDown" or
        "OneTimeSetUp" or "OneTimeTearDown" or "TestFixtureSetUp" or "TestFixtureTearDown" => "NUnit",
        _ => "unknown testing framework"
    };

    /// <summary>
    /// Maps a forbidden namespace to its parent testing framework.
    /// </summary>
    /// <param name="namespaceName">The namespace discovered in a using directive.</param>
    /// <returns>The friendly testing framework name associated with the namespace.</returns>
    private static string GetFrameworkNameFromNamespace(string namespaceName) => namespaceName switch
    {
        var ns when ns.StartsWith("Microsoft.VisualStudio.TestTools.UnitTesting") => "MSTest",
        var ns when ns.StartsWith("NUnit") => "NUnit",
        _ => "unknown testing framework"
    };

    /// <summary>
    /// Determines whether the supplied name belongs to the Microsoft Testing Platform.
    /// </summary>
    /// <param name="name">The fully qualified type or namespace name.</param>
    /// <returns><c>true</c> when the name references Microsoft Testing Platform artifacts; otherwise, <c>false</c>.</returns>
    private static bool IsTestingPlatform(string name) => name.StartsWith("Microsoft.Testing.Platform", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Determines whether the file path points to build output such as <c>bin</c> or <c>obj</c> folders.
    /// </summary>
    /// <param name="path">The file path under analysis.</param>
    /// <returns><c>true</c> when the path resides in build output; otherwise, <c>false</c>.</returns>
    private static bool IsInBuildOutputFolder(string? path)
    {
        if (string.IsNullOrEmpty(path)) return false;

        if (path is not null)
        {
            var p = path.Replace('/', '\\');
            return p.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase) || p.Contains("\\bin\\", StringComparison.OrdinalIgnoreCase);

        }

        return false;
    }

    /// <summary>
    /// Determines whether the syntax tree represents auto-generated code.
    /// </summary>
    /// <param name="tree">The syntax tree to inspect.</param>
    /// <returns><c>true</c> when the file contains an auto-generated header; otherwise, <c>false</c>.</returns>
    private static bool IsAutoGenerated(SyntaxTree tree)
    {
        try
        {
            var text = tree.GetText().ToString();
            var length = Math.Min(512, text.Length);
            return text.AsSpan(0, length).IndexOf("<auto-generated>", StringComparison.OrdinalIgnoreCase) >= 0;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Evaluates analyzer configuration to determine whether the current file should be skipped.
    /// </summary>
    /// <param name="context">The analysis context associated with the syntax node.</param>
    /// <returns><c>true</c> when project metadata disables the analyzer for this file; otherwise, <c>false</c>.</returns>
    private static bool IsIgnoredByProjectConfig(SyntaxNodeAnalysisContext context)
    {
        // Path-based skip for analyzer test assets
        var path = context.Node.SyntaxTree?.FilePath;
        if (!string.IsNullOrEmpty(path) && path is not null && path.IndexOf(".Analyzer.Tests", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return true;
        }

        // Honor simple project hints provided via options
        var provider = context.Options.AnalyzerConfigOptionsProvider;
        if (provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.project_name", out var projectName) &&
            !string.IsNullOrEmpty(projectName) && projectName.EndsWith(".Analyzer.Tests", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }
        if (provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.ignore_projects", out var list) &&
            provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.project_name", out var current))
        {
            var parts = (list ?? string.Empty).Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Any(p => string.Equals(p, current, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Determines whether the current compilation suppresses the conversion diagnostics at the assembly level.
    /// </summary>
    /// <param name="context">The syntax node analysis context.</param>
    /// <returns><c>true</c> when suppression attributes are present; otherwise, <c>false</c>.</returns>
    private static bool HasAssemblySuppression(SyntaxNodeAnalysisContext context)
    {
        try
        {
            var attrs = context.SemanticModel.Compilation.Assembly.GetAttributes();
            return attrs.Any(a => a.AttributeClass?.Name is "SuppressTestFrameworkConversion" or "SuppressTestFrameworkConversionAttribute");
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Tracks using directives already reported per syntax tree to avoid duplicate diagnostics.
    /// </summary>
    private static readonly ConcurrentDictionary<SyntaxTree, ConcurrentDictionary<string, byte>> ReportedNamespaces = new();

    /// <summary>
    /// Adds a namespace to the reported cache and indicates whether it should be reported.
    /// </summary>
    /// <param name="tree">The syntax tree hosting the using directive.</param>
    /// <param name="ns">The namespace discovered.</param>
    /// <returns><c>true</c> when the namespace was not previously reported; otherwise, <c>false</c>.</returns>
    private static bool ShouldReportUsing(SyntaxTree tree, string ns)
    {
        var set = ReportedNamespaces.GetOrAdd(tree, _ => new ConcurrentDictionary<string, byte>(StringComparer.OrdinalIgnoreCase));
        return set.TryAdd(ns, 0);
    }

    /// <summary>
    /// Retrieves a diagnostic descriptor honoring severity overrides supplied via editorconfig.
    /// </summary>
    /// <param name="context">The syntax node analysis context.</param>
    /// <returns>The severity-adjusted descriptor when provided; otherwise, <c>null</c> to fall back to the default rule.</returns>
    private static DiagnosticDescriptor? GetDescriptorWithSeverity(SyntaxNodeAnalysisContext context)
    {
        if (context.Options.AnalyzerConfigOptionsProvider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.severity", out var value))
        {
            switch (value?.Trim().ToLowerInvariant())
            {
                case "suggestion":
                case "info":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Info, true, Description);
                case "silent":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Hidden, true, Description);
                case "warning":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Warning, true, Description);
                case "error":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Error, true, Description);
            }
        }
        return null;
    }
}
