using System;
using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace IndFusion.Analyzers.Testing;

/// <summary>
/// Analyzer that enforces XUnit v3 usage for testing.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class UseXUnitV3Analyzer : DiagnosticAnalyzer
{
    private static readonly LocalizableString Title = "Use XUnit v3 for testing";
    private static readonly LocalizableString MessageFormat = "Use XUnit v3 instead of '{0}' for testing";
    private static readonly LocalizableString Description = "XUnit v3 should be used for all testing instead of other testing frameworks like MSTest or NUnit.";

    private static readonly DiagnosticDescriptor Rule = new(
        DiagnosticIds.UseXUnitV3,
        Title,
        MessageFormat,
        DiagnosticCategories.Testing,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: Description);

    /// <inheritdoc/>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Rule);

    /// <inheritdoc/>
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(AnalyzeAttribute, SyntaxKind.Attribute);
        context.RegisterSyntaxNodeAction(AnalyzeUsingDirective, SyntaxKind.UsingDirective);
    }

    private static void AnalyzeAttribute(SyntaxNodeAnalysisContext context)
    {
        var attribute = (AttributeSyntax)context.Node;
        if (IsIgnoredByProjectConfig(context)) return;
        if (IsAutoGenerated(context.Node.SyntaxTree) || IsInBuildOutputFolder(context.Node.SyntaxTree.FilePath)) return;
        if (HasAssemblySuppression(context)) return;

        var attributeName = attribute.Name.ToString();

        // Allow Microsoft Testing Platform attributes and local wrappers
        var attributeSymbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
        var attrType = attributeSymbol?.ContainingType;
        var attrTypeName = attrType?.ToDisplayString() ?? attributeName;
        if (IsTestingPlatform(attrTypeName)) return;
        
        // Check if this is a locally defined attribute (wrapper) - must check BEFORE name matching
        // If the attribute type is from the current compilation (defined in source), skip it
        if (attrType != null)
        {
            // Check if it's defined in the current source code
            if (attrType.Locations.Any(l => l.IsInSource))
            {
                return;
            }
            
            // Also check if it's NOT from a known test framework namespace
            var ns = attrType.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var isKnownFramework = ns.StartsWith("Microsoft.VisualStudio.TestTools", StringComparison.Ordinal) ||
                                  ns.StartsWith("NUnit", StringComparison.Ordinal) ||
                                  ns == "Xunit" ||
                                  ns == "Xunit.Abstractions";
            
            if (!isKnownFramework)
            {
                // It's a custom attribute not from a known test framework, so skip it
                return;
            }
        }

        // Check for forbidden testing framework attributes
        var forbiddenAttributes = new[]
        {
            "TestMethod",
            "TestClass",
            "TestInitialize",
            "TestCleanup",
            "ClassInitialize",
            "ClassCleanup",
            "AssemblyInitialize",
            "AssemblyCleanup",
            "Test",
            "TestCase",
            "TestFixture",
            "SetUp",
            "TearDown",
            "OneTimeSetUp",
            "OneTimeTearDown",
            "TestFixtureSetUp",
            "TestFixtureTearDown"
        };

        foreach (var forbidden in forbiddenAttributes)
        {
            if (attributeName == forbidden || attributeName.EndsWith("." + forbidden))
            {
                var framework = GetFrameworkName(forbidden);
                var descriptor = GetDescriptorWithSeverity(context) ?? Rule;
                var diagnostic = Diagnostic.Create(
                    descriptor,
                    attribute.GetLocation(),
                    framework);

                context.ReportDiagnostic(diagnostic);
                break;
            }
        }
    }

    private static void AnalyzeUsingDirective(SyntaxNodeAnalysisContext context)
    {
        var usingDirective = (UsingDirectiveSyntax)context.Node;
        if (IsIgnoredByProjectConfig(context)) return;
        if (IsAutoGenerated(context.Node.SyntaxTree) || IsInBuildOutputFolder(context.Node.SyntaxTree.FilePath)) return;

        var namespaceName = usingDirective.Name?.ToString();

        if (namespaceName == null)
        {
            return;
        }

        // Allow current Xunit usage (this is effectively XUnit v3 or the current version)
        if (namespaceName == "Xunit")
        {
            return; // Don't report diagnostic for current Xunit usage
        }

        // Allow Microsoft Testing Platform namespaces
        if (IsTestingPlatform(namespaceName))
        {
            return;
        }

        // Check for other forbidden testing framework namespaces
        var forbiddenNamespaces = new[]
        {
            "Microsoft.VisualStudio.TestTools.UnitTesting",
            "NUnit.Framework",
            "NUnit"
        };

        foreach (var forbidden in forbiddenNamespaces)
        {
            if (namespaceName == forbidden || namespaceName.StartsWith(forbidden + "."))
            {
                // Deduplicate per tree per offending namespace (avoid double-reporting global usings)
                if (!ShouldReportUsing(context.Node.SyntaxTree, namespaceName)) return;

                var framework = GetFrameworkNameFromNamespace(forbidden);
                var descriptor = GetDescriptorWithSeverity(context) ?? Rule;
                var diagnostic = Diagnostic.Create(
                    descriptor,
                    usingDirective.GetLocation(),
                    framework);

                context.ReportDiagnostic(diagnostic);
                break;
            }
        }
    }

    private static string GetFrameworkName(string attributeName) => attributeName switch
    {
        "TestMethod" or "TestClass" or "TestInitialize" or "TestCleanup" or
        "ClassInitialize" or "ClassCleanup" or "AssemblyInitialize" or "AssemblyCleanup" => "MSTest",
        "Test" or "TestCase" or "TestFixture" or "SetUp" or "TearDown" or
        "OneTimeSetUp" or "OneTimeTearDown" or "TestFixtureSetUp" or "TestFixtureTearDown" => "NUnit",
        _ => "unknown testing framework"
    };

    private static string GetFrameworkNameFromNamespace(string namespaceName) => namespaceName switch
    {
        var ns when ns.StartsWith("Microsoft.VisualStudio.TestTools.UnitTesting") => "MSTest",
        var ns when ns.StartsWith("NUnit") => "NUnit",
        _ => "unknown testing framework"
    };

    private static bool IsTestingPlatform(string name) => name.StartsWith("Microsoft.Testing.Platform", StringComparison.OrdinalIgnoreCase);

    private static bool IsInBuildOutputFolder(string? path)
    {
        if (string.IsNullOrEmpty(path)) return false;

        if (path is not null)
        {
            var p = path.Replace('/', '\\');
            return p.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase) || p.Contains("\\bin\\", StringComparison.OrdinalIgnoreCase);

        }

        return false;
    }

    private static bool IsAutoGenerated(SyntaxTree tree)
    {
        try
        {
            var text = tree.GetText().ToString();
            var length = Math.Min(512, text.Length);
            return text.AsSpan(0, length).IndexOf("<auto-generated>", StringComparison.OrdinalIgnoreCase) >= 0;
        }
        catch
        {
            return false;
        }
    }

    private static bool IsIgnoredByProjectConfig(SyntaxNodeAnalysisContext context)
    {
        // Path-based skip for analyzer test assets
        var path = context.Node.SyntaxTree?.FilePath;
        if (!string.IsNullOrEmpty(path) && path is not null && path.IndexOf(".Analyzer.Tests", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return true;
        }

        // Honor simple project hints provided via options
        var provider = context.Options.AnalyzerConfigOptionsProvider;
        if (provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.project_name", out var projectName) &&
            !string.IsNullOrEmpty(projectName) && projectName.EndsWith(".Analyzer.Tests", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }
        if (provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.ignore_projects", out var list) &&
            provider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.project_name", out var current))
        {
            var parts = (list ?? string.Empty).Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Any(p => string.Equals(p, current, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasAssemblySuppression(SyntaxNodeAnalysisContext context)
    {
        try
        {
            var attrs = context.SemanticModel.Compilation.Assembly.GetAttributes();
            return attrs.Any(a => a.AttributeClass?.Name is "SuppressTestFrameworkConversion" or "SuppressTestFrameworkConversionAttribute");
        }
        catch
        {
            return false;
        }
    }

    private static readonly ConcurrentDictionary<SyntaxTree, ConcurrentDictionary<string, byte>> ReportedNamespaces = new();
    private static bool ShouldReportUsing(SyntaxTree tree, string ns)
    {
        var set = ReportedNamespaces.GetOrAdd(tree, _ => new ConcurrentDictionary<string, byte>(StringComparer.OrdinalIgnoreCase));
        return set.TryAdd(ns, 0);
    }

    private static DiagnosticDescriptor? GetDescriptorWithSeverity(SyntaxNodeAnalysisContext context)
    {
        if (context.Options.AnalyzerConfigOptionsProvider.GlobalOptions.TryGetValue("dotnet_diagnostic.EXXER101.severity", out var value))
        {
            switch (value?.Trim().ToLowerInvariant())
            {
                case "suggestion":
                case "info":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Info, true, Description);
                case "silent":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Hidden, true, Description);
                case "warning":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Warning, true, Description);
                case "error":
                    return new DiagnosticDescriptor(DiagnosticIds.UseXUnitV3, Title, MessageFormat, DiagnosticCategories.Testing, DiagnosticSeverity.Error, true, Description);
            }
        }
        return null;
    }
}
