using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using IndFusion.Analyzers;
using IndFusion.Analyzers.Documentation;
using IndFusion.Analyzer.Tests.Testing;
using Shouldly;
using Xunit;

namespace IndFusion.Analyzer.Tests.TestCases.Documentation;

/// <summary>
/// Tests for PublicMembersShouldHaveXmlDocumentationAnalyzer false-positive mitigation scenarios.
/// </summary>
public class PublicMembersShouldHaveXmlDocumentationFalsePositiveTests
{
    //  Story 1.1: Exempt Blazor Partial Components

    /// <summary>
    /// Tests that public members in Blazor partial components are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Blazor_Partial_Components()
    {
        const string testCode = @"
using Microsoft.AspNetCore.Components;

namespace TestProject
{
    public partial class MyComponent : ComponentBase
    {
        public string Title { get; set; } = string.Empty;
        
        public void HandleClick()
        {
        }
        
        public string GetDisplayText()
        {
            return Title;
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.2: Exempt Auto-Generated Files

    /// <summary>
    /// Tests that public members in auto-generated files are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Auto_Generated_Files()
    {
        const string testCode = @"
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

namespace TestProject
{
    public class GeneratedClass
    {
        public string Property { get; set; } = string.Empty;
        
        public void GeneratedMethod()
        {
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.3: Inherit Documentation for Record Members

    /// <summary>
    /// Tests that record members inherit documentation from the record type.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Record_Members_With_Record_Documentation()
    {
        const string testCode = @"
namespace TestProject
{
    /// <summary>
    /// Represents a user in the system.
    /// </summary>
    public record User(string Name, int Age)
    {
        public string GetDisplayName() => Name;
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.4: Exempt DTO/ViewModel Properties

    /// <summary>
    /// Tests that DTO/ViewModel properties are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_DTO_ViewModel_Properties()
    {
        const string testCode = @"
namespace TestProject.Dto
{
    public class UserDto
    {
        public string Name { get; set; } = string.Empty;
        public int Age { get; set; }
        public string Email { get; set; } = string.Empty;
    }
}

namespace TestProject.Vm
{
    public class UserViewModel
    {
        public string DisplayName { get; set; } = string.Empty;
        public bool IsActive { get; set; }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.5: Inherit Documentation from Interface Members

    /// <summary>
    /// Tests that interface implementations inherit documentation from the interface.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Interface_Implementations_With_Interface_Documentation()
    {
        const string testCode = @"
namespace TestProject
{
    /// <summary>
    /// Represents a service for user operations.
    /// </summary>
    public interface IUserService
    {
        /// <summary>
        /// Gets a user by ID.
        /// </summary>
        /// <param name=""id"">The user ID.</param>
        /// <returns>The user.</returns>
        string GetUser(int id);
    }

    public class UserService : IUserService
    {
        public string GetUser(int id)
        {
            return ""User"";
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.6: Exempt Unit Test Classes

    /// <summary>
    /// Tests that public members in unit test classes are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Unit_Test_Classes()
    {
        const string testCode = @"
using Xunit;

namespace TestProject
{
    public class UserServiceTests
    {
        public void Setup()
        {
        }
        
        public string GetTestData()
        {
            return ""test"";
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.7: Aggregate Documentation from Partial Types

    /// <summary>
    /// Tests that partial types aggregate documentation from all parts.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Partial_Types_With_Documentation_On_One_Part()
    {
        const string testCode = @"
namespace TestProject
{
    /// <summary>
    /// Represents a user service.
    /// </summary>
    public partial class UserService
    {
        public void Method1()
        {
        }
    }

    public partial class UserService
    {
        public void Method2()
        {
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.8: Exempt Minimal API and Top-Level Statements

    /// <summary>
    /// Tests that public members in files with top-level statements are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Top_Level_Statements()
    {
        const string testCode = @"
// Top-level statements
var app = WebApplication.CreateBuilder().Build();

namespace TestProject
{
    public class Program
    {
        public static void Main(string[] args)
        {
        }
        
        public static void ConfigureServices()
        {
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.9: Exempt Serialized Fields and Properties

    /// <summary>
    /// Tests that serialized fields and properties are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Serialized_Fields_And_Properties()
    {
        const string testCode = @"
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;

namespace TestProject
{
    public class User
    {
        [JsonPropertyName(""name"")]
        public string Name { get; set; } = string.Empty;
        
        [DataMember]
        public int Age { get; set; }
        
        [Required]
        public string Email { get; set; } = string.Empty;
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Story 1.10: Provide an Opt-Out Attribute

    /// <summary>
    /// Tests that members with AllowUndocumentedMembers attribute are not flagged.
    /// </summary>
    [Fact]
    public void Should_Not_Report_For_Members_With_AllowUndocumentedMembers_Attribute()
    {
        const string testCode = @"
namespace TestProject
{
    public class AllowUndocumentedMembersAttribute : Attribute { }

    [AllowUndocumentedMembers]
    public class UserService
    {
        public void ProcessUser()
        {
        }
        
        public string GetUserData()
        {
            return ""data"";
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldBeEmpty();
    }

     // 

    //  Positive Control Tests

    /// <summary>
    /// Tests that regular public members without documentation are still flagged (positive control).
    /// </summary>
    [Fact]
    public void Should_Report_For_Regular_Public_Members_Without_Documentation()
    {
        const string testCode = @"
namespace TestProject
{
    public class RegularService
    {
        public void ProcessData()
        {
        }
        
        public string GetData()
        {
            return ""data"";
        }
    }
}";

        var diagnostics = AnalyzerTestHelper.RunAnalyzer(testCode, new PublicMembersShouldHaveXmlDocumentationAnalyzer());
        diagnostics.ShouldNotBeEmpty();
        diagnostics.ShouldAllBe(d => d.Id == DiagnosticIds.PublicMembersShouldHaveXmlDocumentation);
    }

     // 
}
