using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace IndTrace.Generators;

[Generator]
public class EnumLookupIncrementalGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the incremental source generation pipeline that discovers enum-model derived types and emits lookup providers.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax cds && cds.BaseList != null,
                transform: static (ctx, _) =>
                {
                    var classSyntax = (ClassDeclarationSyntax)ctx.Node;
                    var model = ctx.SemanticModel;
                    var symbol = model.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
                    return symbol;
                })
            .Where(symbol => symbol?.BaseType?.ToDisplayString() == "IndTrace.Domain.Enum.EnumModel");

        context.RegisterSourceOutput(classDeclarations, (ctx, symbol) =>
        {
            var source = GenerateSource(symbol);
            ctx.AddSource($"{symbol.Name}_Lookup.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.ToDisplayString();
        var className = symbol.Name;
        var lookupClass = $"{className}_LookupProvider";

        var sb = new StringBuilder($@"
// <auto-generated />
#nullable disable
#pragma warning disable CS0169 // Field is never used
#pragma warning disable CS0649 // Field is never assigned
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8625, CS8629
using System.Collections.Generic;
using IndTrace.Domain.Enum;

namespace {ns}
{{
    /// <summary>
    /// Provides lookup data for the <see cref=""{className}""/> enumeration model.
    /// </summary>
    public static class {lookupClass}
    {{
        /// <summary>
        /// Builds the lookup table entries for <see cref=""{className}""/>.
        /// </summary>
        /// <returns>A list of <see cref=""EnumLookUpTable""/> rows mapping values to display names.</returns>
        public static List<EnumLookUpTable> ToLookup() => new()
        {{
");

        foreach (var member in symbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsStatic && SymbolEqualityComparer.Default.Equals(f.Type, symbol)))
        {
            if (member.Name == "Invalid") continue;

            sb.AppendLine($"            new EnumLookUpTable({className}.{member.Name}.Value, \"{member.Name}\", {className}.{member.Name}.DisplayName),");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var text = sb.ToString();
        return text;
    }
}
