classDiagram

	class EnumLookupIncrementalGenerator  {
		+Initialize(IncrementalGeneratorInitializationContext context) void
		-GenerateSource(INamedTypeSymbol symbol) string
	}

	EnumLookupIncrementalGenerator --|> IIncrementalGenerator
